/**
 * Outreach Drafter Agent
 * Generates personalized outreach emails for qualified leads.
 * Drafts require admin approval before sending (human-in-the-loop).
 */

import { prisma } from "@/lib/prisma";
import { llmJson } from "../llm";
import { OUTREACH_SYSTEM_PROMPT, OUTREACH_USER_PROMPT } from "../prompts/outreach";
import { registerAgent, type AgentContext, type AgentRunResult } from "../runner";

interface OutreachDraft {
  subject: string;
  body: string;
  tone: string;
  personalizationUsed: string[];
  callToAction: string;
}

async function outreachDrafterAgent(context: AgentContext): Promise<AgentRunResult> {
  // Find qualified leads that haven't been contacted yet
  const leads = await prisma.lead.findMany({
    where: {
      status: { in: ["QUALIFIED"] },
      leadScore: { gte: 50 },
      emails: { none: {} },
    },
    take: 5,
    orderBy: { leadScore: "desc" },
  });

  if (leads.length === 0) {
    return {
      success: true,
      message: "No qualified leads ready for outreach",
      data: { drafted: 0 },
    };
  }

  let drafted = 0;
  const drafts: Array<{ leadName: string; subject: string }> = [];

  for (const lead of leads) {
    try {
      // Parse stored notes for metadata
      let metadata: Record<string, unknown> = {};
      let qualification: Record<string, unknown> = {};
      try {
        if (lead.notes) {
          metadata = JSON.parse(lead.notes);
          qualification = (metadata.qualification as Record<string, unknown>) || {};
        }
      } catch {
        // notes may not be JSON
      }

      const draft = await llmJson<OutreachDraft>(
        OUTREACH_SYSTEM_PROMPT,
        OUTREACH_USER_PROMPT({
          businessName: lead.businessName,
          contactName: lead.contactName || undefined,
          businessType: (metadata.types as string[])?.join(", ") || undefined,
          city: lead.city || undefined,
          state: lead.state || undefined,
          website: lead.website || undefined,
          qualificationNotes: qualification.suggestedApproach as string || undefined,
        }),
        { temperature: 0.8 }
      );

      // Store as outreach email draft (pending approval)
      await prisma.outreachEmail.create({
        data: {
          leadId: lead.id,
          subject: draft.subject,
          body: draft.body,
          status: "DRAFT",
        },
      });

      // Update lead status
      await prisma.lead.update({
        where: { id: lead.id },
        data: { status: "CONTACTED" },
      });

      // Log activity
      await prisma.leadActivity.create({
        data: {
          leadId: lead.id,
          type: "EMAIL_DRAFTED",
          title: `Outreach email drafted: ${draft.subject}`,
          detail: `Tone: ${draft.tone}. Personalization: ${draft.personalizationUsed.join(", ")}. CTA: ${draft.callToAction}. Generated by run: ${context.runId}`,
        },
      });

      drafted++;
      drafts.push({ leadName: lead.businessName, subject: draft.subject });
    } catch (error) {
      console.error(`Failed to draft outreach for ${lead.businessName}:`, error);
    }
  }

  return {
    success: true,
    message: `Drafted ${drafted} outreach emails awaiting approval`,
    data: {
      drafted,
      drafts,
    },
    recommendations: drafted > 0
      ? [
          {
            type: "outreach_draft",
            title: `${drafted} outreach emails ready for review`,
            description: `AI has drafted ${drafted} personalized outreach emails for qualified leads. Review, edit if needed, and approve to send.`,
            priority: "high" as const,
            actionUrl: "/admin/ai/outreach",
            metadata: { drafts },
          },
        ]
      : [],
  };
}

// Register the agent
registerAgent("outreach_drafter", outreachDrafterAgent);

export { outreachDrafterAgent };
