/**
 * Outreach Drafter Agent
 * Generates personalized outreach emails for qualified leads.
 * Drafts require admin approval before sending (human-in-the-loop).
 */

import { prisma } from "@/lib/prisma";
import { sendRawEmail } from "@/lib/email";
import { llmJson } from "../llm";
import { OUTREACH_SYSTEM_PROMPT, OUTREACH_USER_PROMPT } from "../prompts/outreach";
import { registerAgent, type AgentContext, type AgentRunResult } from "../runner";
import { checkEmailSafety } from "../safety";

interface OutreachDraft {
  subject: string;
  body: string;
  tone: string;
  personalizationUsed: string[];
  callToAction: string;
}

async function outreachDrafterAgent(context: AgentContext): Promise<AgentRunResult> {
  const autoSend = process.env.AI_OUTREACH_AUTO_SEND === "true";

  // Find qualified leads that haven't been contacted yet
  const leads = await prisma.lead.findMany({
    where: {
      status: { in: ["QUALIFIED"] },
      leadScore: { gte: 50 },
      email: { not: "" },
      emails: { none: {} },
    },
    take: 5,
    orderBy: { leadScore: "desc" },
  });

  if (leads.length === 0) {
    return {
      success: true,
      message: "No qualified leads ready for outreach",
      data: { drafted: 0 },
    };
  }

  let drafted = 0;
  let sent = 0;
  const drafts: Array<{ leadName: string; subject: string }> = [];

  for (const lead of leads) {
    try {
      // Parse stored notes for metadata
      let metadata: Record<string, unknown> = {};
      let qualification: Record<string, unknown> = {};
      try {
        if (lead.notes) {
          metadata = JSON.parse(lead.notes);
          qualification = (metadata.qualification as Record<string, unknown>) || {};
        }
      } catch {
        // notes may not be JSON
      }

      const draft = await llmJson<OutreachDraft>(
        OUTREACH_SYSTEM_PROMPT,
        OUTREACH_USER_PROMPT({
          businessName: lead.businessName,
          contactName: lead.contactName || undefined,
          businessType: (metadata.types as string[])?.join(", ") || undefined,
          city: lead.city || undefined,
          state: lead.state || undefined,
          website: lead.website || undefined,
          qualificationNotes: qualification.suggestedApproach as string || undefined,
        }),
        { temperature: 0.8 }
      );

      const emailRecord = await prisma.outreachEmail.create({
        data: {
          leadId: lead.id,
          subject: draft.subject,
          body: draft.body,
          status: autoSend ? "QUEUED" : "DRAFT",
        },
      });

      // Log activity
      await prisma.leadActivity.create({
        data: {
          leadId: lead.id,
          type: "EMAIL_DRAFTED",
          title: `Outreach email drafted: ${draft.subject}`,
          detail: `Tone: ${draft.tone}. Personalization: ${draft.personalizationUsed.join(", ")}. CTA: ${draft.callToAction}. Generated by run: ${context.runId}`,
        },
      });

      drafted++;
      drafts.push({ leadName: lead.businessName, subject: draft.subject });

      if (autoSend) {
        const safety = await checkEmailSafety("outreach_drafter", lead.email);
        if (!safety.allowed) {
          await prisma.outreachEmail.update({
            where: { id: emailRecord.id },
            data: { status: "DRAFT" },
          });
          await prisma.leadActivity.create({
            data: {
              leadId: lead.id,
              type: "EMAIL_SEND_SKIPPED",
              title: "AI outreach held for review",
              detail: safety.reason,
            },
          });
          continue;
        }

        const sendResult = await sendRawEmail({
          to: lead.email,
          subject: draft.subject,
          text: draft.body,
        }).catch(async (error) => {
          await prisma.outreachEmail.update({
            where: { id: emailRecord.id },
            data: { status: "FAILED" },
          });
          await prisma.leadActivity.create({
            data: {
              leadId: lead.id,
              type: "EMAIL_SEND_FAILED",
              title: `Failed to send AI outreach: ${draft.subject}`,
              detail: error instanceof Error ? error.message : "Unknown send error",
            },
          });
          return null;
        });

        if (!sendResult) {
          continue;
        }

        if (sendResult.skipped) {
          await prisma.outreachEmail.update({
            where: { id: emailRecord.id },
            data: { status: "DRAFT" },
          });
          await prisma.leadActivity.create({
            data: {
              leadId: lead.id,
              type: "EMAIL_SEND_SKIPPED",
              title: "AI outreach held for review",
              detail: sendResult.reason,
            },
          });
          continue;
        }

        await prisma.$transaction([
          prisma.outreachEmail.update({
            where: { id: emailRecord.id },
            data: { status: "SENT", sentAt: new Date() },
          }),
          prisma.lead.update({
            where: { id: lead.id },
            data: { status: "CONTACTED", contactedAt: new Date() },
          }),
          prisma.leadActivity.create({
            data: {
              leadId: lead.id,
              type: "EMAIL_SENT",
              title: `Sent AI outreach: ${draft.subject}`,
              detail: sendResult.providerId ? `Resend message ID: ${sendResult.providerId}` : null,
            },
          }),
        ]);
        sent++;
      }
    } catch (error) {
      console.error(`Failed to draft outreach for ${lead.businessName}:`, error);
    }
  }

  return {
    success: true,
    message: autoSend
      ? `Drafted ${drafted} outreach emails and sent ${sent}`
      : `Drafted ${drafted} outreach emails awaiting approval`,
    data: {
      drafted,
      sent,
      drafts,
    },
    recommendations: drafted > 0
      ? [
          {
            type: "outreach_draft",
            title: `${drafted} outreach emails ready for review`,
            description: `AI has drafted ${drafted} personalized outreach emails for qualified leads. Review, edit if needed, and approve to send.`,
            priority: "high" as const,
            actionUrl: "/admin/ai/outreach",
            metadata: { drafts },
          },
        ]
      : [],
  };
}

// Register the agent
registerAgent("outreach_drafter", outreachDrafterAgent);

export { outreachDrafterAgent };
